DROP TABLE DONACION;
DROP TABLE VISUALIZACION;
DROP TABLE CONTENIDO;
DROP TABLE CATEGORIA;
DROP TABLE USUARIO;

CREATE TABLE USUARIO(
    EMAIL VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    FECHANAC DATE NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (EMAIL),
    CONSTRAINT UK_USUARIO_NICKNAME UNIQUE (NICKNAME)
);

CREATE TABLE CATEGORIA(
    CODCATEGORIA NUMERIC(2) NOT NULL,
    NOMBRECATEGORIA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (CODCATEGORIA),
    CONSTRAINT UK_CATEGORIA_NOMBRE UNIQUE (NOMBRECATEGORIA),
	CONSTRAINT CK_CATEGORIA_ESTADO CHECK (NOMBRECATEGORIA IN ('Fortnite', 'LoL','Dota 2', 'Musica'))
);


CREATE TABLE CONTENIDO(
    CODCONTENIDO NUMBER(10) NOT NULL,	
	TITULO VARCHAR(50) NOT NULL,
	FECHAEMISION DATE NOT NULL,
	EMAILUSUARIO VARCHAR(50) NOT NULL,
    CODCATEGORIA NUMERIC(2) NOT NULL,
    DOMINIO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CONTENIDO PRIMARY KEY (CODCONTENIDO),
	CONSTRAINT FK_CONTENIDO_USUARIO FOREIGN KEY (EMAILUSUARIO) REFERENCES USUARIO(EMAIL),
    CONSTRAINT FK_CONTENIDO_CATEGORIA FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA(CODCATEGORIA),
    CONSTRAINT CK_CONTENIDO_DOMINIO CHECK (DOMINIO IN ('PUBLICO', 'PRIVADO'))
);

CREATE TABLE VISUALIZACION(
    CODCONTENIDO NUMBER(10) NOT NULL,
    EMAILUSUARIO VARCHAR(50) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_VISUALIZACION PRIMARY KEY (EMAILUSUARIO, CODCONTENIDO, FECHA),
    CONSTRAINT FK_VISUALIZACION_USUARIO FOREIGN KEY (EMAILUSUARIO) REFERENCES USUARIO(EMAIL),
    CONSTRAINT FK_VISUALIZACION_CONTENIDO FOREIGN KEY (CODCONTENIDO) REFERENCES CONTENIDO(CODCONTENIDO)
);

CREATE TABLE DONACION(
    EMAILORIGEN VARCHAR(50) NOT NULL,
    EMAILDESTINO VARCHAR(50) NOT NULL,
    FECHACREACION DATE NOT NULL,
	FECHAACREDITACION DATE,
    MONTO NUMBER(5) NOT NULL,
    ESTADODONACION VARCHAR(10) NOT NULL,
    CONSTRAINT PK_DONACION PRIMARY KEY (EMAILORIGEN, EMAILDESTINO, FECHACREACION),
    CONSTRAINT FK_DONACION_USUARIOORIG FOREIGN KEY (EMAILORIGEN) REFERENCES USUARIO(EMAIL),
    CONSTRAINT FK_DONACION_USUARIODEST FOREIGN KEY (EMAILDESTINO) REFERENCES USUARIO(EMAIL),
    CONSTRAINT CK_DONACION_USU_ORIG_DEST CHECK (EMAILORIGEN <> EMAILDESTINO),
    CONSTRAINT CK_DONACION_ESTADO CHECK (ESTADODONACION IN ('PENDIENTE', 'APROBADA'))
);
